version: 1.0.{build}
image: Windows Server 2016

environment:
  DOCKER_USER:
    secure: LjNiW/ZWrfVIJn3Mc9foeg==
  DOCKER_PASS:
    secure: 4gsl5WiqIztEWhL5fuhp9X0qT/mKg9fYzKYUUPf5WStIuNddv0fvIKGmvvyuFzzd
install:
  - docker version

build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\test.ps1

deploy_script:
  - ps: .\deploy.ps1
