################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# Docker configuration backend
################################################################
[docker]
domain = "docker.local"
watch = true
endpoint = "npipe:////./pipe/docker_engine"

# Use Swarm Mode services as data provider
#
# Optional
# Default: false
#
#swarmmode = true

# Sample entrypoint configuration when using ACME
[entryPoints]
  [entryPoints.http]
  address = ":80"
